### PR TITLE
Add Heroku Support and modified some pieces of code

### PR DESCRIPTION
**Pull request by kaif-00z**

### CODE REVIEW

**Comment by kaif-00z** [comment]
All Done!

**Comment by amitkr-codes** [comment]
Revert `__main__.py` commit too.

**Comment by kaif-00z** [comment]
> Revert `__main__.py` commit too.

Looks Good 😕

**Comment by kaif-00z** [comment]
> Revert `__main__.py` commit too.

Done 😑

**Comment by amitkr-codes** [comment]
> > Revert `__main__.py` commit too.
> 
> Done 😑

Pro

**Comment by amitkr-codes** [comment]
Tick heroku support in readme

**Comment by kaif-00z** [comment]
ufff

**Comment by kaif-00z** [comment]
> Tick heroku support in readme

Dn

**Comment by amitkr-codes** [comment]
Where heroku deploy button?

**Comment by kaif-00z** [comment]
> Where heroku deploy button?

Full abuse bazi

**Comment by kaif-00z** [comment]
> Where heroku deploy button?

Done

**Pull request merged**
